### ISSUE TITLE
Unable to install airavata-mft with Python3.11

### ISSUE THREAD

**Issue by nandarshan** [apache/airavata-mft#104] opened 2023-06-20 15:33 UTC
**Describe the bug**
Unable to install airavata-mft with Python3.11. I get the following errors: 
-> ERROR: Could not build wheels for grpcio, grpcio-tools, which is required to install pyproject.toml-based projects <br />

**To Reproduce**
To reproduce, <br />
1) Install python3.11 <br />
2) If you have already installed airavata-mft, create a virtual environment with python3.11. <br />
3) To create venv: <code> python3.11 -m venv \<path\> </code> <br />
4) To activate venv: <code> source \<path\>/bin/activate </code> <br />
5) <code> python3.11 -m pip install airavata-mft-cli </code>
6) Error I got is shown in the following screenshot.

<img width="1536" alt="Screenshot 2023-06-20 at 10 51 33 AM" src="https://github.com/apache/airavata-mft/assets/124709697/7641650d-de5a-4fb9-b2da-5cedf8b6afb2">

**Expected behavior**
To install successfully <br />

**Additional context 1**
System Configuration: <br />
1) Processor: <code>2.4 GHz 8-Core Intel Core i9</code>
2) Operating System: <code>macOS Ventura Version 13.4</code> 
3) Python version: <code>3.11.4</code> <br />

**Additional context 2**
Even though [this](https://github.com/apache/airavata-mft/issues/71) issue is for M1/M2 Macs, I found this issue similar to the above error. This issue had a solution which is to install a specific version of grpcio and grpcio-tools. But installing those gave an error in python3.11<br />
On entering the following to the testvenv activated above: <br/>
<code>python3.11 -m pip install grpcio==1.47.0rc1</code> <br />
I got the following error <br />
<img width="1536" alt="Screenshot 2023-06-20 at 11 17 08 AM" src="https://github.com/apache/airavata-mft/assets/124709697/f422764b-a1ab-4076-8392-970c9fec1496">

I tried the second command in the solution of [this](https://github.com/apache/airavata-mft/issues/71) issue.
On entering the following to the testenv activated above: <br />
<code>python3 -m pip install grpcio-tools==1.47.0rc1</code><br />
I got the following error <br />

<img width="1536" alt="Screenshot 2023-06-20 at 11 25 07 AM" src="https://github.com/apache/airavata-mft/assets/124709697/1758f4f0-c171-4c6c-a5b8-805645132d21">

<br /><br />

**Additional context 3**
I was able to successfully install the airavata-mft after downgrading to python3.10. Since I was not able to install airavata-mft with python3.11, I am posting this issue.

**EDIT**: Added backslashes before \< and \> in the markdown so that \<path\> is visible in step 3 and step 4 of the "To Reproduce" section.

**Comment by machristie** [comment] 2023-06-20 17:48
I ran into this with the airavata-django-portal-sdk, I found the following versions to work well (this was 6 months ago):

    grpcio-tools==1.48.2 ; python_version < "3.7"
    grpcio-tools==1.51.1 ; python_version >= "3.7"
    grpcio==1.48.2 ; python_version < "3.7"
    grpcio==1.51.1 ; python_version >= "3.7"

https://github.com/apache/airavata-django-portal-sdk/blob/master/requirements.txt#L8-L11

Also, with the SDK we needed to support Python 3.6, but I wouldn't recommend that for MFT.

**Comment by machristie** [comment] 2023-06-21 21:22
I think the problem is here: https://github.com/apache/airavata-mft/blob/master/python-sdk/pyproject.toml#L20. The pyproject.toml requires specific versions of grpcio and grpcio-tools, so even though you've already upgraded them, it reverts to these older versions.

I think you could try just removing grpcio and grpcio-tools from the requires list in pyproject.toml.

**Comment by AYPfzU92g7M4aH39-ODVPzqxll48V** [comment] 2023-06-24 00:43
Thank you so much. It worked. I removed grpcio and grpcio-tools from pyproject.toml in the python-sdk folder and built the sdk locally. It got installed successfully.

**Comment by DImuthuUpe** [comment] 2023-08-20 18:19
Closing this as the issue was resolved

**Closed by DImuthuUpe** 2023-08-20 18:19 UTC

**Comment by ZhenmeiOng** [comment] 2024-02-16 01:42
> I think the problem is here: https://github.com/apache/airavata-mft/blob/master/python-sdk/pyproject.toml#L20. The pyproject.toml requires specific versions of grpcio and grpcio-tools, so even though you've already upgraded them, it reverts to these older versions.
> 
> I think you could try just removing grpcio and grpcio-tools from the requires list in pyproject.toml.

how do you do that? I can't find the file on my local files.
